
name: Create Release
on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          ver="$(echo ${{ github.ref_name }} | sed -e 's/^v//')"
          echo "ver=${ver}" >> $GITHUB_ENV

      - name: Parse Changes
        run: |
          sed \
            -e '/./,$!d' \
            -e '/^$/,$d' \
            -e 's/^\t/  /' \
            -e '3 s/^.*$/### Changes:/' \
            changelog.txt | tail -n+2 > release_notes.tmp

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 'Version ${{ env.ver }}'
          body_path: release_notes.tmp
